-- dim_surcharge_type | Códigos distintos de YCODOS1..7
SELECT DISTINCT surcharge_code
FROM (
    SELECT YCODOS1 AS surcharge_code FROM [PAGAR E RECEBER] WHERE YCODOS1 IS NOT NULL AND YCODOS1 <> ''
    UNION
    SELECT YCODOS2 FROM [PAGAR E RECEBER] WHERE YCODOS2 IS NOT NULL AND YCODOS2 <> ''
    UNION
    SELECT YCODOS3 FROM [PAGAR E RECEBER] WHERE YCODOS3 IS NOT NULL AND YCODOS3 <> ''
    UNION
    SELECT YCODOS4 FROM [PAGAR E RECEBER] WHERE YCODOS4 IS NOT NULL AND YCODOS4 <> ''
    UNION
    SELECT YCODOS5 FROM [PAGAR E RECEBER] WHERE YCODOS5 IS NOT NULL AND YCODOS5 <> ''
    UNION
    SELECT YCODOS6 FROM [PAGAR E RECEBER] WHERE YCODOS6 IS NOT NULL AND YCODOS6 <> ''
    UNION
    SELECT YCODOS7 FROM [PAGAR E RECEBER] WHERE YCODOS7 IS NOT NULL AND YCODOS7 <> ''
) codes
