"""
Padrões comuns de encoding que aparecem em múltiplos domínios.
Fragmentos de palavras — aplicados com str.replace (não precisa ser palavra inteira).

REGRA: colocar os padrões MAIORES primeiro (ex: "??O" antes de "?O")
para evitar substituição parcial.
"""

COMMON_FIXES = {
    # ══ Padrões com dois ?? (ÇÃ, ÇÕ) — processar PRIMEIRO ══
    "A??O": "AÇÃO",
    "A??ES": "AÇÕES",
    "FUN??O": "FUNÇÃO",
    "FUN??ES": "FUNÇÕES",
    "SE??O": "SEÇÃO",
    "SE??ES": "SEÇÕES",
    "POSI??O": "POSIÇÃO",
    "POSI??ES": "POSIÇÕES",
    "CONDI??O": "CONDIÇÃO",
    "CONDI??ES": "CONDIÇÕES",
    "EXCE??O": "EXCEÇÃO",
    "EXCE??ES": "EXCEÇÕES",
    "INSTALA??O": "INSTALAÇÃO",
    "INSTALA??ES": "INSTALAÇÕES",
    "OPERA??O": "OPERAÇÃO",
    "OPERA??ES": "OPERAÇÕES",
    "CALIBRA??O": "CALIBRAÇÃO",
    "MANUTEN??O": "MANUTENÇÃO",
    "REDU??O": "REDUÇÃO",
    "FIXA??O": "FIXAÇÃO",
    "PROTE??O": "PROTEÇÃO",
    "AUTOMA??O": "AUTOMAÇÃO",
    "REFRIGERA??O": "REFRIGERAÇÃO",
    "VENTILA??O": "VENTILAÇÃO",
    "DISTRIBUI??O": "DISTRIBUIÇÃO",
    "IMPORTA??O": "IMPORTAÇÃO",
    "EXPORTA??O": "EXPORTAÇÃO",
    "INFORMA??O": "INFORMAÇÃO",
    "INFORMA??ES": "INFORMAÇÕES",
    "EDUCA??O": "EDUCAÇÃO",
    "PRODU??O": "PRODUÇÃO",
    "CONSTRU??O": "CONSTRUÇÃO",
    "SOLU??O": "SOLUÇÃO",
    "SOLU??ES": "SOLUÇÕES",
    "COMUNICA??O": "COMUNICAÇÃO",
    "CLASSIFICA??O": "CLASSIFICAÇÃO",
    "ORGANIZA??O": "ORGANIZAÇÃO",
    "MOVIMENTA??O": "MOVIMENTAÇÃO",
    "DOCUMENTA??O": "DOCUMENTAÇÃO",
    "ADMINISTRA??O": "ADMINISTRAÇÃO",
    "LIQUIDA??O": "LIQUIDAÇÃO",
    "NEGOCIA??O": "NEGOCIAÇÃO",
    "ATUALIZA??O": "ATUALIZAÇÃO",
    "FATURA??O": "FATURAÇÃO",
    "TRIBUTA??O": "TRIBUTAÇÃO",
    "COMPENSA??O": "COMPENSAÇÃO",
    "DEVOLU??O": "DEVOLUÇÃO",
    "INSPE??O": "INSPEÇÃO",
    "RECEP??O": "RECEPÇÃO",
    "CORRE??O": "CORREÇÃO",
    "ALTERA??O": "ALTERAÇÃO",
    "CANCELA??O": "CANCELAÇÃO",
    "APROVA??O": "APROVAÇÃO",

    # ══ Padrões com um ? (Ã, Á, Â, É, Ê, Í, Ó, Ô, Õ, Ú, Ç) ══
    # Ã / Õ
    "S?O": "SÃO",
    "N?O": "NÃO",
    "GR?O": "GRÃO",
    "M?O": "MÃO",
    "ALEM?O": "ALEMÃO",
    "CRIST?O": "CRISTÃO",
    "CAPIT?O": "CAPITÃO",
    "JO?O": "JOÃO",
    "CONEX?O": "CONEXÃO",
    "PRESS?O": "PRESSÃO",
    "DIMENS?O": "DIMENSÃO",
    "EXTENS?O": "EXTENSÃO",
    "TENS?O": "TENSÃO",
    "EXPANS?O": "EXPANSÃO",
    "COLIS?O": "COLISÃO",
    "EMISS?O": "EMISSÃO",
    "PERMISS?O": "PERMISSÃO",
    "COMISS?O": "COMISSÃO",
    "DIVIS?O": "DIVISÃO",
    "REVIS?O": "REVISÃO",
    "PROVIS?O": "PROVISÃO",
    "VIS?O": "VISÃO",

    # Ç
    "PRE?O": "PREÇO",
    "SERVI?O": "SERVIÇO",
    "SERVI?OS": "SERVIÇOS",
    "CABE?A": "CABEÇA",
    "BALAN?A": "BALANÇA",
    "MUDAN?A": "MUDANÇA",
    "SEGURAN?A": "SEGURANÇA",
    "CONFIAN?A": "CONFIANÇA",
    "ALIAN?A": "ALIANÇA",
    "LIDERAN?A": "LIDERANÇA",
    "ESPERAN?A": "ESPERANÇA",
    "PRESEN?A": "PRESENÇA",
    "ISEN??O": "ISENÇÃO",

    # É / Ê
    "COM?RCIO": "COMÉRCIO",
    "NEG?CIOS": "NEGÓCIOS",
    "NEG?CIO": "NEGÓCIO",
    "GER?NCIA": "GERÊNCIA",
    "REFER?NCIA": "REFERÊNCIA",
    "EMERG?NCIA": "EMERGÊNCIA",
    "FREQU?NCIA": "FREQUÊNCIA",
    "EXPERI?NCIA": "EXPERIÊNCIA",
    "CONSIST?NCIA": "CONSISTÊNCIA",

    # Á
    "?GUA": "ÁGUA",
    "?REA": "ÁREA",
    "M?QUINA": "MÁQUINA",
    "V?LVULA": "VÁLVULA",
    "L?MINA": "LÂMINA",
    "C?MARA": "CÂMARA",
    "DIN?MICA": "DINÂMICA",

    # Ó / Ô
    "LOG?STICA": "LOGÍSTICA",
    "MEC?NICA": "MECÂNICA",
    "HIDR?ULICA": "HIDRÁULICA",
    "PNEUM?TICA": "PNEUMÁTICA",
    "EL?TRICA": "ELÉTRICA",
    "ELETR?NICA": "ELETRÔNICA",
    "QU?MICA": "QUÍMICA",
    "T?CNICA": "TÉCNICA",
    "T?CNICO": "TÉCNICO",
    "T?RMICO": "TÉRMICO",
    "T?RMICO": "TÉRMICO",
    "AUT?NOMO": "AUTÔNOMO",
    "TEL?FONE": "TELEFONE",
    "PER?ODO": "PERÍODO",
    "RELAT?RIO": "RELATÓRIO",
    "ESCRIT?RIO": "ESCRITÓRIO",
    "AUDIT?RIO": "AUDITÓRIO",
    "REPOSIT?RIO": "REPOSITÓRIO",
    "TERRIT?RIO": "TERRITÓRIO",
    "TEMPOR?RIO": "TEMPORÁRIO",
    "PROVIS?RIO": "PROVISÓRIO",
    "NECESS?RIO": "NECESSÁRIO",
    "VOLUNT?RIO": "VOLUNTÁRIO",
    "COMENT?RIO": "COMENTÁRIO",
    "INVENT?RIO": "INVENTÁRIO",
    "ARMAZ?M": "ARMAZÉM",

    # Ú
    "?NICO": "ÚNICO",
    "?LTIMO": "ÚLTIMO",
    "N?MERO": "NÚMERO",
    "N?MEROS": "NÚMEROS",
    "P?BLICO": "PÚBLICO",
    "M?SICA": "MÚSICA",
    
# Adicionar ao COMMON_FIXES:
    "ABRA?ADEIRA": "ABRAÇADEIRA",
    "BALAN?A": "BALANÇA",
    "DESCART?VEIS": "DESCARTÁVEIS",
    "DESCART?VEL": "DESCARTÁVEL",
    "M?DICO": "MÉDICO",
    "M?DICA": "MÉDICA",
    "M?DICOS": "MÉDICOS",
    "REABILITA??O": "REABILITAÇÃO",
    "INCLUS?O": "INCLUSÃO",
    "PAIX?O": "PAIXÃO",
    "ACELERA??O": "ACELERAÇÃO",
    "?CULOS": "ÓCULOS",
    "?NIBUS": "ÔNIBUS",
    "RENASCEN?A": "RENASCENÇA",
    "ANHANG?ERA": "ANHANGUERA"
}
